name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: .

    - name: Run Playwright tests
      run: npx playwright test --config playwright.service.config.ts --workers=20
      working-directory: .
      env:
        PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
        PLAYWRIGHT_SERVICE_ACCESS_TOKEN: ${{ secrets.PLAYWRIGHT_SERVICE_ACCESS_TOKEN }}

    # - name: Publish Playwright tests
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Playwright tests
    #     path: ./playwright-report/
